### ISSUE TITLE
Implement Game Log

### ISSUE THREAD

**Issue by marc-fulgar** [adish-co/poker_plus_api#124]
1. When Dealer clicks `Start Game`:
`"Dealer started the game"`
2. When Player clicks `Join`:
`"[Player name] joined the session"`
3. After game-joining timeout:
`"Dealer is dealing the cards"`
4. When Player sets their Cards:
`"[Player name] has set their cards"`
5. When all players have set their cards:
`"All players have set their cards."`
`"Dealer may start the round."`
6. When Dealer clicks `Round Start`:
`"Dealer has started the round."`
`"[Player 1 name] has paid the small blind."`
`"[Player 2 name] has paid the big blind."`
`"Waiting for [Player 3 name]'s action..."`
7. When Player 3 chooses an action:
`"[Player 3 name] [action]s."` ("Roxanne folds." or "Paco raises.")
`"Waiting for [Player 4 name]'s action..."`
8. When the round ends:
`"Dealer is now setting the [flop/turn/river]."`
9. When Dealer sets the flop/turn/river:
`"Dealer has set the [flop/turn/river]."`
10. When the Session ends:
`"This game has ended."`

**Comment by roxanneeullo** [comment]
PR #139 
ui: arman-miranda/poker-plus-ui-react#43
